"""Tests for ContentClusterer processor.

Covers:
- AC-020: Multi-source content on same event/topic auto-clustered into a group
- AC-T024-1: Clustering based on cosine similarity of content vectors, configurable threshold
- AC-T024-2: New content tries existing clusters first; creates new cluster if no match
- AC-T024-3: Cluster topic generated by LLM
- AC-T024-4: Fallback uses TF-IDF + cosine similarity for clustering
- AC-T024-5: Cluster centroid vector updated when new content joins
"""

from __future__ import annotations

from unittest.mock import AsyncMock, MagicMock

import pytest
from intellisource.llm.processors.cluster import ContentClusterer

from intellisource.pipeline.base import BaseProcessor
from intellisource.pipeline.context import PipelineContext

# ---------------------------------------------------------------------------
# Sample data
# ---------------------------------------------------------------------------

SAMPLE_TITLE = "Global Climate Summit Concludes with New Agreements"
SAMPLE_BODY = (
    "World leaders gathered in Geneva for the annual climate summit. "
    "New emissions targets were agreed upon by 150 nations."
)
SAMPLE_EMBEDDING = [0.1, 0.2, 0.3, 0.4, 0.5]

RELATED_TITLE = "Climate Summit: Key Outcomes and Reactions"
RELATED_BODY = (
    "The Geneva climate summit concluded with ambitious pledges. "
    "Environmental groups praised the new emissions framework."
)
RELATED_EMBEDDING = [0.12, 0.19, 0.31, 0.38, 0.52]

UNRELATED_TITLE = "New Programming Language Released"
UNRELATED_BODY = "A new systems programming language was announced today."
UNRELATED_EMBEDDING = [0.9, 0.1, 0.0, 0.8, 0.0]


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def mock_gateway() -> AsyncMock:
    """LLM gateway that returns a generated cluster topic."""
    gateway = AsyncMock()
    result = MagicMock()
    result.content = "Global Climate Summit Agreements"
    result.metadata = {
        "input_tokens": 120,
        "output_tokens": 10,
        "latency_ms": 150.0,
        "model": "gpt-4o-mini",
    }
    gateway.complete = AsyncMock(return_value=result)
    return gateway


@pytest.fixture
def mock_gateway_failing() -> AsyncMock:
    """LLM gateway that raises an exception."""
    gateway = AsyncMock()
    gateway.complete = AsyncMock(side_effect=Exception("LLM unavailable"))
    return gateway


@pytest.fixture
def mock_vector_store_with_match() -> MagicMock:
    """Vector store that finds a matching existing cluster."""
    store = MagicMock()
    cluster = MagicMock()
    cluster.id = "cluster-001"
    cluster.topic = "Climate Summit"
    cluster.centroid = [0.11, 0.21, 0.29, 0.41, 0.51]
    store.find_nearest_cluster = MagicMock(return_value=cluster)
    store.update_centroid = MagicMock()
    store.create_cluster = MagicMock()
    return store


@pytest.fixture
def mock_vector_store_no_match() -> MagicMock:
    """Vector store that finds no matching cluster."""
    store = MagicMock()
    store.find_nearest_cluster = MagicMock(return_value=None)
    new_cluster = MagicMock()
    new_cluster.id = "cluster-new-001"
    new_cluster.topic = "Global Climate Summit Agreements"
    store.create_cluster = MagicMock(return_value=new_cluster)
    store.update_centroid = MagicMock()
    return store


@pytest.fixture
def mock_call_log() -> AsyncMock:
    """Create a mock LLMCallLog recorder."""
    return AsyncMock()


@pytest.fixture
def pipeline_context() -> PipelineContext:
    """PipelineContext with sample content for clustering."""
    ctx = PipelineContext()
    ctx.set("title", SAMPLE_TITLE)
    ctx.set("body_text", SAMPLE_BODY)
    ctx.set("embedding", SAMPLE_EMBEDDING)
    return ctx


@pytest.fixture
def clusterer_with_match(
    mock_gateway: AsyncMock,
    mock_vector_store_with_match: MagicMock,
    mock_call_log: AsyncMock,
) -> ContentClusterer:
    """ContentClusterer where vector store finds a matching cluster."""
    return ContentClusterer(
        gateway=mock_gateway,
        vector_store=mock_vector_store_with_match,
        call_log=mock_call_log,
    )


@pytest.fixture
def clusterer_no_match(
    mock_gateway: AsyncMock,
    mock_vector_store_no_match: MagicMock,
    mock_call_log: AsyncMock,
) -> ContentClusterer:
    """ContentClusterer where vector store finds no matching cluster."""
    return ContentClusterer(
        gateway=mock_gateway,
        vector_store=mock_vector_store_no_match,
        call_log=mock_call_log,
    )


# ---------------------------------------------------------------------------
# ContentClusterer implements BaseProcessor
# ---------------------------------------------------------------------------


class TestContentClustererInterface:
    """Verify ContentClusterer satisfies the BaseProcessor contract."""

    def test_is_subclass_of_base_processor(self) -> None:
        """ContentClusterer must be a subclass of BaseProcessor."""
        assert issubclass(ContentClusterer, BaseProcessor)

    def test_has_process_method(self, clusterer_with_match: ContentClusterer) -> None:
        """ContentClusterer instance must have a callable process method."""
        assert callable(getattr(clusterer_with_match, "process", None))

    def test_process_returns_pipeline_context(
        self,
        clusterer_with_match: ContentClusterer,
        pipeline_context: PipelineContext,
    ) -> None:
        """process() must return a PipelineContext instance."""
        result = clusterer_with_match.process(pipeline_context)
        assert isinstance(result, PipelineContext)


# ---------------------------------------------------------------------------
# AC-T024-1: Clustering based on cosine similarity, configurable threshold
# ---------------------------------------------------------------------------


class TestClusterThresholdConfig:
    """Verify cluster_threshold is configurable with default 0.75."""

    def test_default_threshold_is_075(
        self,
        mock_gateway: AsyncMock,
        mock_vector_store_with_match: MagicMock,
        mock_call_log: AsyncMock,
    ) -> None:
        """Default cluster_threshold must be 0.75."""
        processor = ContentClusterer(
            gateway=mock_gateway,
            vector_store=mock_vector_store_with_match,
            call_log=mock_call_log,
        )
        assert processor.cluster_threshold == 0.75

    def test_custom_threshold(
        self,
        mock_gateway: AsyncMock,
        mock_vector_store_with_match: MagicMock,
        mock_call_log: AsyncMock,
    ) -> None:
        """cluster_threshold must be settable via constructor."""
        processor = ContentClusterer(
            gateway=mock_gateway,
            vector_store=mock_vector_store_with_match,
            call_log=mock_call_log,
            cluster_threshold=0.80,
        )
        assert processor.cluster_threshold == 0.80

    def test_threshold_passed_to_vector_store(
        self,
        mock_gateway: AsyncMock,
        mock_vector_store_with_match: MagicMock,
        mock_call_log: AsyncMock,
        pipeline_context: PipelineContext,
    ) -> None:
        """process() must pass cluster_threshold to vector_store.find_nearest_cluster."""
        processor = ContentClusterer(
            gateway=mock_gateway,
            vector_store=mock_vector_store_with_match,
            call_log=mock_call_log,
            cluster_threshold=0.80,
        )
        processor.process(pipeline_context)

        mock_vector_store_with_match.find_nearest_cluster.assert_called_once()
        call_args = mock_vector_store_with_match.find_nearest_cluster.call_args
        args, kwargs = call_args
        # threshold should be passed as 0.80
        passed_threshold = kwargs.get("threshold", args[1] if len(args) > 1 else None)
        assert passed_threshold == 0.80


# ---------------------------------------------------------------------------
# AC-020 / AC-T024-2: Auto-clustering and join-or-create logic
# ---------------------------------------------------------------------------


class TestClusterAssignment:
    """Verify new content joins existing cluster or creates new one."""

    def test_joins_existing_cluster_when_match_found(
        self,
        clusterer_with_match: ContentClusterer,
        pipeline_context: PipelineContext,
    ) -> None:
        """When vector store finds a matching cluster, content joins it."""
        result_ctx = clusterer_with_match.process(pipeline_context)
        assert result_ctx.get("cluster_id") == "cluster-001"

    def test_creates_new_cluster_when_no_match(
        self,
        clusterer_no_match: ContentClusterer,
        pipeline_context: PipelineContext,
        mock_vector_store_no_match: MagicMock,
    ) -> None:
        """When no matching cluster, a new cluster must be created."""
        result_ctx = clusterer_no_match.process(pipeline_context)
        mock_vector_store_no_match.create_cluster.assert_called_once()
        assert result_ctx.get("cluster_id") == "cluster-new-001"

    def test_vector_store_searched_with_embedding(
        self,
        clusterer_with_match: ContentClusterer,
        pipeline_context: PipelineContext,
        mock_vector_store_with_match: MagicMock,
    ) -> None:
        """process() must call find_nearest_cluster with the content embedding."""
        clusterer_with_match.process(pipeline_context)

        mock_vector_store_with_match.find_nearest_cluster.assert_called_once()
        call_args = mock_vector_store_with_match.find_nearest_cluster.call_args
        args, kwargs = call_args
        passed_embedding = args[0] if args else kwargs.get("embedding")
        assert passed_embedding == SAMPLE_EMBEDDING

    def test_multiple_contents_same_cluster(
        self,
        mock_gateway: AsyncMock,
        mock_vector_store_with_match: MagicMock,
        mock_call_log: AsyncMock,
    ) -> None:
        """Multiple related contents should be assigned to the same cluster."""
        processor = ContentClusterer(
            gateway=mock_gateway,
            vector_store=mock_vector_store_with_match,
            call_log=mock_call_log,
        )

        ctx1 = PipelineContext()
        ctx1.set("title", SAMPLE_TITLE)
        ctx1.set("body_text", SAMPLE_BODY)
        ctx1.set("embedding", SAMPLE_EMBEDDING)

        ctx2 = PipelineContext()
        ctx2.set("title", RELATED_TITLE)
        ctx2.set("body_text", RELATED_BODY)
        ctx2.set("embedding", RELATED_EMBEDDING)

        result1 = processor.process(ctx1)
        result2 = processor.process(ctx2)

        # Both should join the same existing cluster
        assert result1.get("cluster_id") == "cluster-001"
        assert result2.get("cluster_id") == "cluster-001"


# ---------------------------------------------------------------------------
# AC-T024-3: Cluster topic generated by LLM
# ---------------------------------------------------------------------------


class TestClusterTopicGeneration:
    """Verify LLM generates topic for new clusters."""

    def test_llm_called_for_new_cluster_topic(
        self,
        clusterer_no_match: ContentClusterer,
        pipeline_context: PipelineContext,
        mock_gateway: AsyncMock,
    ) -> None:
        """When creating a new cluster, LLM must be called to generate topic."""
        clusterer_no_match.process(pipeline_context)
        mock_gateway.complete.assert_called()

    def test_llm_not_called_when_joining_existing_cluster(
        self,
        clusterer_with_match: ContentClusterer,
        pipeline_context: PipelineContext,
        mock_gateway: AsyncMock,
    ) -> None:
        """When joining an existing cluster, LLM should NOT be called for topic."""
        clusterer_with_match.process(pipeline_context)
        mock_gateway.complete.assert_not_called()

    def test_generated_topic_passed_to_create_cluster(
        self,
        clusterer_no_match: ContentClusterer,
        pipeline_context: PipelineContext,
        mock_vector_store_no_match: MagicMock,
    ) -> None:
        """LLM-generated topic must be passed to vector_store.create_cluster."""
        clusterer_no_match.process(pipeline_context)

        mock_vector_store_no_match.create_cluster.assert_called_once()
        call_args = mock_vector_store_no_match.create_cluster.call_args
        args, kwargs = call_args
        # topic should be the LLM-generated text
        passed_topic = kwargs.get("topic", args[1] if len(args) > 1 else None)
        assert passed_topic == "Global Climate Summit Agreements"

    def test_topic_set_in_context(
        self,
        clusterer_no_match: ContentClusterer,
        pipeline_context: PipelineContext,
    ) -> None:
        """Cluster topic should be set in context for downstream processors."""
        result_ctx = clusterer_no_match.process(pipeline_context)
        topic = result_ctx.get("cluster_topic")
        assert topic is not None
        assert isinstance(topic, str)
        assert len(topic) > 0


# ---------------------------------------------------------------------------
# AC-T024-4: Fallback uses TF-IDF + cosine similarity
# ---------------------------------------------------------------------------


class TestFallbackLogic:
    """Verify degradation to TF-IDF + cosine similarity when LLM fails."""

    def test_fallback_on_gateway_error_creates_cluster_with_tfidf_topic(
        self,
        mock_gateway_failing: AsyncMock,
        mock_vector_store_no_match: MagicMock,
        mock_call_log: AsyncMock,
        pipeline_context: PipelineContext,
    ) -> None:
        """When LLM fails, fallback should use TF-IDF keywords as topic."""
        processor = ContentClusterer(
            gateway=mock_gateway_failing,
            vector_store=mock_vector_store_no_match,
            call_log=mock_call_log,
        )
        result_ctx = processor.process(pipeline_context)

        # Should still create a cluster (not raise)
        mock_vector_store_no_match.create_cluster.assert_called_once()
        # Fallback indicator should be set
        assert result_ctx.get("cluster_fallback") is True

    def test_fallback_topic_derived_from_tfidf(
        self,
        mock_gateway_failing: AsyncMock,
        mock_vector_store_no_match: MagicMock,
        mock_call_log: AsyncMock,
        pipeline_context: PipelineContext,
    ) -> None:
        """Fallback topic should be derived from TF-IDF keywords, not empty."""
        processor = ContentClusterer(
            gateway=mock_gateway_failing,
            vector_store=mock_vector_store_no_match,
            call_log=mock_call_log,
        )
        result_ctx = processor.process(pipeline_context)

        topic = result_ctx.get("cluster_topic")
        assert topic is not None
        assert isinstance(topic, str)
        assert len(topic) > 0

    def test_fallback_method_indicator(
        self,
        mock_gateway_failing: AsyncMock,
        mock_vector_store_no_match: MagicMock,
        mock_call_log: AsyncMock,
        pipeline_context: PipelineContext,
    ) -> None:
        """Fallback path should set cluster_method to 'tfidf'."""
        processor = ContentClusterer(
            gateway=mock_gateway_failing,
            vector_store=mock_vector_store_no_match,
            call_log=mock_call_log,
        )
        result_ctx = processor.process(pipeline_context)
        assert result_ctx.get("cluster_method") == "tfidf"

    def test_normal_path_method_indicator(
        self,
        clusterer_no_match: ContentClusterer,
        pipeline_context: PipelineContext,
    ) -> None:
        """Normal path (LLM success) should set cluster_method to 'llm'."""
        result_ctx = clusterer_no_match.process(pipeline_context)
        assert result_ctx.get("cluster_method") == "llm"


# ---------------------------------------------------------------------------
# AC-T024-5: Centroid updated when new content joins
# ---------------------------------------------------------------------------


class TestCentroidUpdate:
    """Verify cluster centroid vector updated when content joins."""

    def test_centroid_updated_on_join(
        self,
        clusterer_with_match: ContentClusterer,
        pipeline_context: PipelineContext,
        mock_vector_store_with_match: MagicMock,
    ) -> None:
        """When content joins existing cluster, update_centroid must be called."""
        clusterer_with_match.process(pipeline_context)

        mock_vector_store_with_match.update_centroid.assert_called_once()
        call_args = mock_vector_store_with_match.update_centroid.call_args
        args, kwargs = call_args
        # Should pass cluster_id and new embedding
        passed_cluster_id = args[0] if args else kwargs.get("cluster_id")
        passed_embedding = args[1] if len(args) > 1 else kwargs.get("new_embedding")
        assert passed_cluster_id == "cluster-001"
        assert passed_embedding == SAMPLE_EMBEDDING

    def test_centroid_not_updated_on_new_cluster_creation(
        self,
        clusterer_no_match: ContentClusterer,
        pipeline_context: PipelineContext,
        mock_vector_store_no_match: MagicMock,
    ) -> None:
        """When creating a new cluster, update_centroid should NOT be called."""
        clusterer_no_match.process(pipeline_context)
        mock_vector_store_no_match.update_centroid.assert_not_called()


# ---------------------------------------------------------------------------
# Edge cases / boundary conditions
# ---------------------------------------------------------------------------


class TestEdgeCases:
    """Boundary conditions and edge cases for cluster processing."""

    def test_empty_body_text(
        self,
        mock_gateway: AsyncMock,
        mock_vector_store_no_match: MagicMock,
        mock_call_log: AsyncMock,
    ) -> None:
        """Processing with empty body_text should not raise."""
        processor = ContentClusterer(
            gateway=mock_gateway,
            vector_store=mock_vector_store_no_match,
            call_log=mock_call_log,
        )
        ctx = PipelineContext()
        ctx.set("title", "Some Title")
        ctx.set("body_text", "")
        ctx.set("embedding", [0.0])
        result = processor.process(ctx)
        assert isinstance(result, PipelineContext)
        assert result.get("cluster_id") is not None

    def test_missing_embedding_raises(
        self,
        mock_gateway: AsyncMock,
        mock_vector_store_no_match: MagicMock,
        mock_call_log: AsyncMock,
    ) -> None:
        """When embedding is missing from context, should raise ValueError or KeyError."""
        processor = ContentClusterer(
            gateway=mock_gateway,
            vector_store=mock_vector_store_no_match,
            call_log=mock_call_log,
        )
        ctx = PipelineContext()
        ctx.set("title", "Some Title")
        ctx.set("body_text", "Some body")
        # No embedding set
        with pytest.raises((ValueError, KeyError)):
            processor.process(ctx)

    def test_vector_store_error_during_search_degrades_gracefully(
        self,
        mock_gateway: AsyncMock,
        mock_call_log: AsyncMock,
        pipeline_context: PipelineContext,
    ) -> None:
        """When vector store search fails, processor should degrade gracefully."""
        failing_store = MagicMock()
        failing_store.find_nearest_cluster = MagicMock(
            side_effect=Exception("Vector store unavailable")
        )
        new_cluster = MagicMock()
        new_cluster.id = "fallback-cluster-001"
        failing_store.create_cluster = MagicMock(return_value=new_cluster)
        failing_store.update_centroid = MagicMock()

        processor = ContentClusterer(
            gateway=mock_gateway,
            vector_store=failing_store,
            call_log=mock_call_log,
        )
        # Should not raise; should create a new cluster as fallback
        result_ctx = processor.process(pipeline_context)
        assert isinstance(result_ctx, PipelineContext)
        assert result_ctx.get("cluster_id") is not None
